# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 16:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=5)),
                ('colour', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Trousers', 'Trousers'), ('Shirts', 'Shirts'), ('Skirts', 'Skirts'), ('Underwear', 'Underwear')], max_length=30)),
                ('photo', models.ImageField(upload_to='img/')),
                ('photo_alt', models.CharField(default='img alt', max_length=20)),
            ],
        ),
    ]
