# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='', upload_to='Product'),
        ),
    ]
