# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='', upload_to=b''),
        ),
    ]
