# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171211_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
