"""
Django settings for shop_proj project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

#To import secret keys not held on GitHub
from .private import *

import stripe
from django.conf import settings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%yxc&s2vg&-y)2f@3%ix_m6@3y9vlr10350^gnib4*o=pm2vn&'

#A test customer stripe token (allows repeated test use, rather than a one off paymen token) 
STRIPE_TEST_TOKEN = 'cus_C5Y4XV57a4s0xz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
    'accounts',    
    'django_forms_bootstrap',
    'products',    
    'purchase',    
    'orders',    
    'core',    
    'checkout',        
    'easy_thumbnails',
    'debug_toolbar'
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
   INTERNAL_IPS = ('127.0.0.1', 'localhost',)


DEBUG_TOOLBAR_CONFIG = {
       'INTERCEPT_REDIRECTS': False,
   }




ROOT_URLCONF = 'shop_proj.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'


# If going to add App specific img/css then use:
# STATICFILES_DIRS = (os.path.join(
#    BASE_DIR, "my_app", "static"),)

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"), ("products", "static"), ("purchase", "static"), ("cart", "static"), ("checkout", "static"), ("orders", "static"), ("core", "static"),)





#Setting authorisation to use the defined model, not default
AUTH_USER_MODEL = 'accounts.User'



#Stripe Environment Variables:
STRIPE_PUBLISHABLE = os.getenv('STRIPE_PUBLISHABLE', 'pk_test_zkkJLlqQ1Tc9XhPXQhJi7QZC')
#STRIPE_SECRET is in private.py, which is ignroed by GIT, to prevent it being uploaded to GitHub
stripe.api_key = settings.STRIPE_SECRET


#To force Django to use the bespoke email/pw authentication, not the default username/pw
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.EmailAuth',
)


# PayPal Settings
# Where PayPal should return our customer after they've bought our products.
SITE_URL = 'http://127.0.0.1:8000'
#Used by Django-Paypal to record transactions in the database. However, we're not going to be using it
PAYPAL_NOTIFY_URL = 'http://127.0.0.1/a-very-hard-to-guess-url/'
# This is the email address of the person who will be given the funds for any transactions. 
# For us, that will be the *merchant* email address that we setup earlier in the developer section of the PayPal website
PAYPAL_RECEIVER_EMAIL = 'paul_cheeseman@zoho.com'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

'''
THUMBNAIL_ALIASES = {
    '': {
            'list-small': {'size': (75, 40), 'upscale': True,},
            'list-medium': {'size': (150, 80), 'upscale': True,},
            'list-large': {'size': (400, 400), 'upscale': True,}
    },
}
'''

THUMBNAIL_ALIASES = {
    '': {
            'list-small': {'size': (100, 50), 'crop': 'scale', 'upscale': True,},
            'list-medium': {'size': (200, 100), 'crop': 'scale', 'upscale': True,},
            'list-large': {'size': (300, 150), 'crop': 'scale', 'upscale': True,}
    },
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
 )
