# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20171111_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
