# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171122_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
