# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
