# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 11:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Trousers', 'Trousers'), ('Shirts', 'Shirts'), ('Skirts', 'Skirts'), ('Underwear', 'Underwear')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
