# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171107_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.IntegerField(default=0),
        ),
    ]
