# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171117_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_custID',
            field=models.CharField(default='Not set', max_length=100),
        ),
    ]
