# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180106_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
