# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='user',
            name='credit_card',
            field=models.IntegerField(default=0),
        ),
    ]
