# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171117_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_custID',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
